Q_IMPORT_PLUGIN(Detail);
Q_IMPORT_PLUGIN(DetailFooter);
Q_IMPORT_PLUGIN(DetailHeader);
Q_IMPORT_PLUGIN(Overlay);
Q_IMPORT_PLUGIN(PageFooter);
Q_IMPORT_PLUGIN(PageHeader);
Q_IMPORT_PLUGIN(Summary);
Q_IMPORT_PLUGIN(Title);

Q_IMPORT_PLUGIN(Page);
Q_IMPORT_PLUGIN(Printer);
Q_IMPORT_PLUGIN(Renderer);
Q_IMPORT_PLUGIN(Script);

Q_IMPORT_PLUGIN(DatasetCSV);
Q_IMPORT_PLUGIN(DatasetFileSystem);
Q_IMPORT_PLUGIN(DatasetModel);
Q_IMPORT_PLUGIN(DatasetSQL);

Q_IMPORT_PLUGIN(ExportPDF);
//Q_IMPORT_PLUGIN(ExportSVG);

Q_IMPORT_PLUGIN(Arc);
Q_IMPORT_PLUGIN(Barcode);
Q_IMPORT_PLUGIN(Chart);
Q_IMPORT_PLUGIN(Chord);
Q_IMPORT_PLUGIN(Ellipse);
Q_IMPORT_PLUGIN(Image);
Q_IMPORT_PLUGIN(Line);
Q_IMPORT_PLUGIN(Memo);
Q_IMPORT_PLUGIN(Pie);
Q_IMPORT_PLUGIN(Rectangle);

Q_IMPORT_PLUGIN(SerializerXML);

Q_IMPORT_PLUGIN(StorageFileSystem);
Q_IMPORT_PLUGIN(StorageGIT);
Q_IMPORT_PLUGIN(StorageResource);
Q_IMPORT_PLUGIN(StorageSQL);
