#ifndef PLUGINS_COMMON_H
#define PLUGINS_COMMON_H

#define SUIT_NAMESPACE Standard
#define USING_SUIT_NAMESPACE using namespace SUIT_NAMESPACE;
#define SUIT_NAMESPACE_STR "Standard"
#define SUIT_BEGIN_NAMESPACE namespace SUIT_NAMESPACE {
#define SUIT_END_NAMESPACE }

//#define QT_BEGIN_NAMESPACE namespace SUIT_NAMESPACE {
//#define QT_END_NAMESPACE }

#endif //PLUGINS_COMMON_H
