Document: cutereport
Title: Debian cutereport Manual
Author: <insert document author here>
Abstract: This manual describes what cutereport is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cutereport/cutereport.sgml.gz

Format: postscript
Files: /usr/share/doc/cutereport/cutereport.ps.gz

Format: text
Files: /usr/share/doc/cutereport/cutereport.text.gz

Format: HTML
Index: /usr/share/doc/cutereport/html/index.html
Files: /usr/share/doc/cutereport/html/*.html
